mislabel_detection:
  datasets:
    - click
    - apsfail
    - phoneme
    - wind
    - pol
    - cpu
    - 2dplanes
  hidden_neurons: 100
  activation_function: relu
  learning_rate: 0.01
  optimizer: adam
  batch_size: 32
  data_points: 200
  test_points: 200
  flip_ratio: 0.1
  max_iter: 1000
  methods:
    - Shapley
    - Banzhaf
    - LOO
    - Beta1-4
    - Beta1-16
    - Beta4-1
    - Beta16-1
  n_repeat: 5

weighted_acc:
  model: LinearRegression
