mislabel_detection:
  MNIST:
    model: LeNet
    batch_size: 128
    learning_rate: 0.001
    optimizer: Adam
    data_points: 2000
  FMNIST:
    model: LeNet
    batch_size: 128
    learning_rate: 0.001
    optimizer: Adam
    data_points: 2000
  CIFAR10:
    model: TwoLayerMLP
    hidden_neurons: 256
    activation_function: ReLU
    batch_size: 128
    learning_rate: 0.001
    optimizer: Adam
    data_points: 2000
  default:
    model: TwoLayerMLP
    hidden_neurons: 100
    activation_function: ReLU
    learning_rate: 0.01
    optimizer: Adam
    batch_size: 32
    data_points: 200
  specific_batch_size:
    Creditcard: 128
    Apsfail: 128
    Click: 128
    CPU: 128
  specific_data_points:
    Click: 1000
    Phoneme: 500
